# Generated by Django 6.0.2 on 2026-02-09 20:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Famille',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=100, unique=True, verbose_name='Référence')),
                ('nom', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nom du produit')),
                ('barcode', models.CharField(max_length=100, unique=True, verbose_name='Code-barres')),
                ('nbr_days_alert', models.PositiveIntegerField(default=30, verbose_name='Jours avant alerte péremption')),
                ('nbr_qnt_alert', models.PositiveIntegerField(default=1, verbose_name='Seuil stock minimum')),
                ('famille', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='produits', to='core.famille')),
            ],
        ),
        migrations.CreateModel(
            name='Lot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField()),
                ('date_entree', models.DateField()),
                ('date_fin', models.DateField(verbose_name='Date de péremption')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lots', to='core.produit')),
            ],
            options={
                'ordering': ['date_fin'],
            },
        ),
    ]
